### ISSUE TITLE
Redo Gallery

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#1026]
- [x] Static desktop structure #1081
- [x] Popup (click image) #1082
- [x] Navbar #1083
- [x] Mobile #1084
- [x] Gallery images stores in S3 instead of this repo #774 
- [x] Dynamic image loading #1085
- [x] Lazy load images #1118
- [x] Gallery thumbnail images #1133 
- [x] Fix GitHub Actions #1125

**Comment by peterkos** [comment]
Blocked; let's get BH out!

**Comment by peterkos** [comment]
"WordArt gallery" @sjmiller7 @cbaudouinjr

**Comment by cbaudouinjr** [comment]
![wordart](https://user-images.githubusercontent.com/22222538/102003673-03d7aa00-3cd8-11eb-84e1-7078dbdeafc3.png)

**Comment by peterkos** [comment]
https://khang-nd.github.io/7.css/ :eyes:
