### ISSUE TITLE
BrickHack 8 Site - Initial Release

### ISSUE THREAD

**Issue by sjmiller7** [codeRIT/brickhack.io#1246]
To go out before winter break

Content can be found in Notion [here](https://www.notion.so/brickhackclub/BrickHack-8-Site-Content-9aa4b49ff06140068b293046546ff720)

Design can be found in Figma [here](https://www.figma.com/file/ZR9Mb4xNRrnoRZoX0bCWsX/BrickHack-Websites?node-id=432%3A97)

This is the base branch that will be merged into the site. Different sections from this release will branch off of here.

To do:
- [x] Gut a copy of bh7 and add in all general styles
- [ ] FAQ section (easy) #1250
- [ ] Hero section (easy) #1247 
- [ ] About section (harder) #1248
- [ ] Contact/Footer section (hardest) #1249
